# Generated by Django 4.1.13 on 2024-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file_app', '0002_useraccount_is_active_useraccount_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
